# fly.toml file generated for redbull-api on 2022-11-07T13:39:07-05:00

app = "redbull-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  MOGODB_URI = "mongodb+srv://sandwich:sandwich@cluster0.4tmzof4.mongodb.net/redbull-backend-api?retryWrites=true&w=majority"
  CLIENT_ORIGIN="https://euphonious-yeot-7b70c6.netlify.app"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
